name: v2rp3
description: "A new Flutter project."
publish_to: 'none'
version: 1.2.8+1

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  http: ^1.6.0
  intl: ^0.18.1
  image_picker: ^0.8.6
  path: ^1.8.1
  shared_preferences: ^2.2.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^19.5.0
  mobile_scanner: ^3.4.1
  flutter_slidable: ^3.0.0
  cached_network_image: ^3.2.0
  curved_navigation_bar: ^1.0.3
  badges: ^3.1.1
  dio: ^5.3.2
  quickalert: ^1.0.2
  url_launcher: ^6.1.14
  liquid_pull_to_refresh: ^3.0.1
  data_table_2: ^2.7.2
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  win32: ^5.5.0
  flutter_plugin_android_lifecycle: ^2.0.33
  image_picker_android: ^0.8.13+10
  path_provider_android: ^2.2.22
  shared_preferences_android: ^2.4.18
  sqflite: ^2.4.2
  url_launcher_android: ^6.3.28

flutter_icons:
  android: true
  ios: true
  image_path: "images/appicon.png"

flutter:
  uses-material-design: true
  assets:
    - images/
